In [1]:
from sklearn.datasets import make_blobs
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_samples, silhouette_score
from sklearn.cluster import AgglomerativeClustering

import matplotlib.pyplot as plt
import matplotlib.cm as cm
import numpy as np


In [3]:
X = [0 for i in range(9)]
y = [0 for i in range(9)]
#                0,    1,     2,     3,     4,      5,      6,      7,      8
n_samples_ = [1000, 5000, 10000, 10000, 50000, 100000, 100000, 100000, 100000]
n_features_ = [  5,    5,     5,    10,     5,      5,     10,     15,      5]
centers_ = [     4,    4,     4,     8,     4,      4,      4,      4,      8]

for i in range(9):
    X[i], y[i] = make_blobs(
        n_samples = n_samples_[i],
        n_features = n_features_[i],
        centers = centers_[i],
        cluster_std=(1),
        center_box=(-10.0, 10.0),
        shuffle=True,
        random_state=123,
    )

In [4]:
count = 0
for x in X:
    print("dataset: ", count)
    float_array = [[float(value) for value in sub_array] for sub_array in x.tolist()]
    file_path = 'C:/Users/matte/k-means/dataset' + str(count) + '.txt'
    print(file_path)
    with open(file_path, 'w') as file:
        for array in float_array:
            string = ""
            for element in array:
                string += str(element) + ','
            string = string[:-1]
            string += '\n'
            file.write(string)
    
    count = count + 1

dataset:  0
C:/Users/matte/k-means/dataset0.txt
dataset:  1
C:/Users/matte/k-means/dataset1.txt
dataset:  2
C:/Users/matte/k-means/dataset2.txt
dataset:  3
C:/Users/matte/k-means/dataset3.txt
dataset:  4
C:/Users/matte/k-means/dataset4.txt
dataset:  5
C:/Users/matte/k-means/dataset5.txt
dataset:  6
C:/Users/matte/k-means/dataset6.txt
dataset:  7
C:/Users/matte/k-means/dataset7.txt
dataset:  8
C:/Users/matte/k-means/dataset8.txt


In [9]:
centroids = [0 for i in range(9)]
for i in range(10):
    print("dataset: ", i)
    kmeans = KMeans(centers_[i])
    kmeans.fit(X[i])
    centroids[i] = kmeans.cluster_centers_
    print(centroids[i])

dataset:  0
[[ 4.93826966 -6.35118675 -6.39597854  0.67836025  0.65299858]
 [-3.15622754  4.5988347  -1.14809541 -8.74384277 -2.09275879]
 [-1.4775032   9.5263173   3.66962567 -0.26616827 -2.11147811]
 [ 3.83836441 -4.2416108  -5.43770762  0.977451    4.3439719 ]]
dataset:  1
[[-3.18146887  4.60971772 -1.21968646 -8.79173213 -2.00154981]
 [ 3.95579268 -4.29147542 -5.43365161  1.0660917   4.38170484]
 [-1.52271022  9.65889172  3.71025253 -0.37023597 -2.14602929]
 [ 4.77661959 -6.36896134 -6.55483353  0.63155244  0.5970093 ]]
dataset:  2
[[-3.1806054   4.63073329 -1.19677097 -8.77427662 -2.03987529]
 [ 3.95533053 -4.26459982 -5.44387483  1.0522834   4.38847823]
 [-1.55199083  9.62206898  3.67026929 -0.3731056  -2.15801427]
 [ 4.76307752 -6.3612275  -6.49521934  0.64517714  0.60878612]]
dataset:  3
[[-3.12794723  4.5475229  -1.22499337 -8.8301232  -2.02968515  4.75376045
  -6.34333332 -6.47334065  0.6007978   0.6410075 ]
 [ 3.97383168 -4.27945317 -5.45130485  1.06844459  4.42331014 -1.583

In [5]:
#scrip for evauluete calculation time of sklearn's Kmeans 0 1 2 4 5
import time

def time_evalueation(dataset_num):
    iter_num = 30
    time_execution = 0
    for i in range(iter_num):
        start = time.time()
        kmeans = KMeans(4, random_state=i)
        kmeans.fit(X[dataset_num])
        end = time.time()
        time_execution = time_execution + (end - start)

    print('dataset' + str(dataset_num) + ': ' + str(time_execution/iter_num))

time_evalueation(0)
time_evalueation(1)
time_evalueation(2)
time_evalueation(4)
time_evalueation(5)


dataset0: 0.064828888575236
dataset1: 0.05276029904683431
dataset2: 0.08367555936177572
dataset4: 0.33585414091746013
dataset5: 0.5790135065714518


In [44]:
dataset 0

initial centroid 0: -1.5557586380927755,10.018285800078493,2.0494790687361206,-1.071002134770219,-0.47958092682516984
initial centroid 1: -0.9650279785400214,8.776171262668665,3.8890435330817588,0.4289636271717442,-0.9896590446923781
initial centroid 2: 5.402890691837405,-5.899295242700605,-6.712291465486588,-0.84158547770639,-0.04416476157530047
initial centroid 3: 3.7893149917685665,-5.138968196852097,-5.718590299246535,-1.7722937238028997,2.617846291201414
    
------------------------------------------------------------------------------------
thresholdCondition: true
iteration: 3
bannedK: []
------------------------------------------------------------------------------------
Execution time: 94198 ms
------------------------------------------------------------------------------------
0       ,-3.1562278,4.5988336,-1.1480954,-8.743847,-2.0927591
1       ,-1.4775028,9.526317,3.6696246,-0.26616827,-2.1114788
2       ,4.9382687,-6.351184,-6.3959794,0.67836016,0.6529987
3       ,3.8383658,-4.2416115,-5.4377065,0.9774507,4.3439713

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

convergenza non alla soluzione ottima globale

initial centroid 0: 3.8653069717940753,-3.843015632899215,-4.582435179792341,1.3712327173512218,4.73514932517142
initial centroid 1: -1.0349358508610111,10.35874966296615,2.8458797252957595,0.16589044287024923,-2.875281320538603
initial centroid 2: -0.5815749178314726,9.41293674773455,3.238665361413566,-0.5806895551735041,-1.1766427805472408
initial centroid 3: -1.9943205741623806,5.085773039200867,-2.2378921797331506,-8.943612647421178,-3.02439955491879

------------------------------------------------------------------------------------
thresholdCondition: true
iteration: 9
bannedK: []
------------------------------------------------------------------------------------
Execution time: 251465 ms
------------------------------------------------------------------------------------

0       ,4.388318,-5.2964034,-5.9168444,0.8279054,2.4984856
1       ,-1.8627104,10.072547,3.8698196,0.10799697,-2.574567
2       ,-1.127582,9.030126,3.4877703,-0.6060587,-1.6908092
3       ,-3.156227,4.5988345,-1.1480949,-8.743847,-2.092759

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
initial centroid 0: -3.085199655488015,3.4294301902770057,-0.8846421981212382,-9.794844720809,-0.9851784993242256
initial centroid 1: 4.275061464498595,-6.219623404662697,-4.687797215527473,1.296663690342974,2.0294505221132315
initial centroid 2: 3.3206729086927904,-5.597815880782063,-6.132589528585696,2.290920668625832,2.969166396762749
initial centroid 3: -2.529475483331659,9.925147421114845,4.039017347777252,0.8606546523308469,-2.322524815136865
    
    ------------------------------------------------------------------------------------
thresholdCondition: true
iteration: 3
bannedK: []
------------------------------------------------------------------------------------
Execution time: 100643 ms
------------------------------------------------------------------------------------

0       ,-3.1562269,4.598834,-1.1480953,-8.743844,-2.0927594
1       ,4.9382687,-6.351184,-6.3959794,0.67836016,0.6529987
2       ,3.838365,-4.24161,-5.437706,0.9774509,4.3439717
3       ,-1.4775031,9.5263195,3.6696248,-0.2661683,-2.111479



SyntaxError: invalid syntax (3405187438.py, line 1)

In [ ]:
dataset 1
initial centroid 0: -2.7570120581198703,9.963439561426142,4.150269272215506,0.8630651594993011,-2.449119783335913
initial centroid 1: -0.7787434425696443,8.177569686786015,4.628084925755638,-2.122438566525653,-1.4414235214289801
initial centroid 2: 4.994282888464991,-5.7766830794660935,-7.103994454861256,0.9772997721554757,-0.08058843996120835
initial centroid 3: 5.700371671183509,-6.220227134257008,-6.700062361070034,0.36370937842715784,2.1309989537508853
    
------------------------------------------------------------------------------------
thresholdCondition: true
iteration: 4
------------------------------------------------------------------------------------
Execution time: 121833 ms
------------------------------------------------------------------------------------
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
initial centroid 0: 3.706176654479492,-6.86326361914475,-7.303033796290443,0.4148438022699912,0.5412834426845122
initial centroid 1: -2.61638874057931,4.889471360105585,0.07833851384411372,-8.884216766815893,-2.499556256737475
initial centroid 2: 6.259847219817477,-3.524846518346598,-5.208316630109803,1.7434213286189766,5.6536270879014605
initial centroid 3: -2.421549732321499,7.638448468199,3.204424495408087,-0.20081208664251407,-2.3630332195289983

------------------------------------------------------------------------------------
thresholdCondition: true
iteration: 3
bannedK: []
------------------------------------------------------------------------------------
Execution time: 100476 ms
------------------------------------------------------------------------------------
0       ,4.776621,-6.368959,-6.5548334,0.63155186,0.5970095
1       ,-3.1814704,4.6097174,-1.2196869,-8.791735,-2.0015476
2       ,3.9557889,-4.291478,-5.4336524,1.0660919,4.3817034
3       ,-1.5227102,9.658885,3.7102542,-0.37023592,-2.146029


++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
initial centroid 0: -3.710969730444546,4.403717552204821,-0.08470578682917118,-8.210075219255344,-1.4660277497190681
initial centroid 1: 3.204210262161964,-3.788009807433708,-3.8969376558884132,2.6309095063307404,5.211597599967867
initial centroid 2: 5.589188291174133,-6.839311568376051,-6.504695366624638,-0.492291822963312,-1.87832599087118
initial centroid 3: -1.3650657290676416,9.98388286294334,2.575508488802288,-0.7037226371526952,-1.2273147583626751

------------------------------------------------------------------------------------
thresholdCondition: true
iteration: 2
bannedK: []
------------------------------------------------------------------------------------
Execution time: 76115 ms
------------------------------------------------------------------------------------

0       ,-3.1814673,4.6097145,-1.2196863,-8.791731,-2.0015492
1       ,3.9561906,-4.2924986,-5.4342422,1.0657109,4.3803716
2       ,4.776876,-6.369601,-6.55514,0.631586,0.5953137
3       ,-1.5227108,9.658899,3.7102547,-0.370236,-2.1460288

In [ ]:
dataset 2

initial centroid 0: -2.7788778561547884,3.4428033655926304,-1.2532796446665688,-8.80426764794046,-1.0303036744109733
initial centroid 1: -3.5951254612146695,1.603169389675081,-0.8647095352068301,-10.162880775463192,-2.816359685505941
initial centroid 2: 4.217215025958489,-6.051683730269178,-4.899396881915761,0.32819546475878403,6.054358320139894
initial centroid 3: 4.461979655541793,-5.639415581957465,-7.228049077637638,1.3426491027615386,0.6146783819343814

------------------------------------------------------------------------------------
thresholdCondition: true
iteration: 3
------------------------------------------------------------------------------------
Execution time: 95989 ms
------------------------------------------------------------------------------------

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

initial centroid 0: -2.1739868347093605,8.765656517370884,3.7092851498950057,-0.3754297019272708,-1.6924464599847409
initial centroid 1: 4.908399175148248,-6.322476213055921,-6.716014584011218,0.600411803440519,-0.6206545013712532
initial centroid 2: -1.05833604867097,10.141624666885972,1.8016964624279468,0.18642656107375832,-2.13786662791908
initial centroid 3: 4.312315906729629,-8.836348752703584,-6.439058223995244,-0.2827428435730365,0.592163303355208
    
------------------------------------------------------------------------------------
thresholdCondition: true
iteration: 5
bannedK: []
------------------------------------------------------------------------------------
Execution time: 149892 ms
------------------------------------------------------------------------------------
0       ,-3.1806037,4.630734,-1.196773,-8.774282,-2.0398755
1       ,3.9553301,-4.2645993,-5.4438725,1.052284,4.3884826
2       ,-1.5519902,9.622077,3.670267,-0.3731053,-2.1580172
3       ,4.7630763,-6.361228,-6.495211,0.64517725,0.60878605

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

initial centroid 0: 3.053056973331746,-5.7024242619134755,-4.351269183612132,1.2072525273997117,5.722180338134194
initial centroid 1: 2.200475331376298,-4.542396032163774,-4.750286585337321,-0.7157279379720922,2.4914277416825352
initial centroid 2: 4.358611212658947,-6.158021716689329,-5.3974125683510366,1.7463701292325087,1.0715039901796197
initial centroid 3: 3.4824665213287114,-3.877409155599137,-5.725253359091989,1.04381471441559,4.570376267238076

------------------------------------------------------------------------------------
thresholdCondition: false
iteration: 24
bannedK: []
------------------------------------------------------------------------------------
Execution time: 624941 ms
------------------------------------------------------------------------------------

0       ,3.5041537,-4.6855955,-5.226825,1.5952166,4.3931475
1       ,-2.3662968,7.126395,1.2367486,-4.5736904,-2.098946
2       ,4.7632613,-6.3631883,-6.4958005,0.64671236,0.60457057
3       ,4.3797636,-3.8754401,-5.6496544,0.5403498,4.37763
    

In [ ]:
dataset 3

initial centroid 0: 2.1280599476760025,-7.684558922845805,-1.8778441997112172,-1.181096604434287,5.942541625187235,-3.911054664460252,-0.12126815390106027,9.81967696131907,1.1661896521102455,3.0197265185775075
initial centroid 1: -9.133138345214057,6.859531037217001,3.546502211314411,0.21469970365469593,-1.8091225553445158,-5.091440141285348,-1.3398220169843054,3.2190032222332006,7.133680564009613,-0.23901605029736422
initial centroid 2: 4.094016509283636,7.134843071450469,5.3412967895807535,1.1743284390787756,4.332166638729674,-3.632440409601796,-2.7175603833248383,-4.296047159894456,-2.497088727161719,1.9773692822954152
initial centroid 3: 3.5083052065522184,-5.443684621608716,-4.606416072322476,1.0089041594276273,5.837955981035712,-0.6456707123729428,9.385857338748513,3.2469271700342914,-0.3579896270255327,-1.9674396182577998
initial centroid 4: -10.790861916999477,-1.6167119384777098,-1.8998015066766123,-0.6018832202328646,-2.8379997385533593,-3.140068478807862,-2.082721475199085,8.416468909654984,9.65188098497485,0.8212710495977507
initial centroid 5: 2.6532418565952427,-6.7632395983572895,-2.5614478976702255,-1.5664157882797012,7.566150878710924,-5.998585189874704,-1.1687648860291484,9.63396834234673,1.6806713913762388,1.3712255330710075
initial centroid 6: -6.7686852303479546,7.583570900531021,1.8924650674083465,4.181343188616825,-9.339617073937514,3.8004075536122306,1.8830528073076822,-7.347705885267321,-8.577028719846941,4.0164138066926185
initial centroid 7: 6.486353414271516,-5.030963106559316,-5.9604258028778405,0.9059545748327194,4.411565170853445,-2.2142859888956887,8.228581289465058,4.308931852519473,-0.5165384151353529,-1.0285659173762336

------------------------------------------------------------------------------------
thresholdCondition: false
iteration: 24
------------------------------------------------------------------------------------
Execution time: 700123 ms
------------------------------------------------------------------------------------

0       ,3.0247464,4.349354,3.5152798,2.8622072,5.6549916,-5.943947,1.2430357,-5.2532244,-5.1081214,2.0640328
1       ,-3.1279469,4.5475264,-1.2249937,-8.830126,-2.029684,4.75376,-6.3433337,-6.4733396,0.60079753,0.6410073
2       ,-7.889104,2.599185,0.33755973,0.36466044,-2.3108077,-3.8365152,-1.5558751,5.7629876,8.209049,0.132314612
3       ,3.973828,-4.2794523,-5.451305,1.068445,4.423311,-1.5839357,9.65662,3.7028058,-0.38173068,-2.1440992
4       ,2.0315905,-7.472626,-3.4018042,-1.9629518,6.6198525,-4.4066944,-0.5529822,9.763134,0.32896784,1.9363539
5       ,-8.089121,7.706249,2.5225677,4.423077,-9.719744,1.9118168,1.142232,-6.8212852,-6.963107,3.924271
6       ,2.2708273,-7.490483,-4.016895,-1.4070169,7.8457127,-5.200826,-0.09157311,9.477303,-0.19929539,2.0344815
7       ,3.0355477,-8.06089,-3.608754,-1.8306476,7.4993806,-5.2487645,-0.2587621,9.791032,1.050154,2.7134616

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

initial centroid 0: 2.1280599476760025,-7.684558922845805,-1.8778441997112172,-1.181096604434287,5.942541625187235,-3.911054664460252,-0.12126815390106027,9.81967696131907,1.1661896521102455,3.0197265185775075
initial centroid 1: -9.133138345214057,6.859531037217001,3.546502211314411,0.21469970365469593,-1.8091225553445158,-5.091440141285348,-1.3398220169843054,3.2190032222332006,7.133680564009613,-0.23901605029736422
initial centroid 2: 4.094016509283636,7.134843071450469,5.3412967895807535,1.1743284390787756,4.332166638729674,-3.632440409601796,-2.7175603833248383,-4.296047159894456,-2.497088727161719,1.9773692822954152
initial centroid 3: 3.5083052065522184,-5.443684621608716,-4.606416072322476,1.0089041594276273,5.837955981035712,-0.6456707123729428,9.385857338748513,3.2469271700342914,-0.3579896270255327,-1.9674396182577998
initial centroid 4: -10.790861916999477,-1.6167119384777098,-1.8998015066766123,-0.6018832202328646,-2.8379997385533593,-3.140068478807862,-2.082721475199085,8.416468909654984,9.65188098497485,0.8212710495977507
initial centroid 5: 2.6532418565952427,-6.7632395983572895,-2.5614478976702255,-1.5664157882797012,7.566150878710924,-5.998585189874704,-1.1687648860291484,9.63396834234673,1.6806713913762388,1.3712255330710075
initial centroid 6: -6.7686852303479546,7.583570900531021,1.8924650674083465,4.181343188616825,-9.339617073937514,3.8004075536122306,1.8830528073076822,-7.347705885267321,-8.577028719846941,4.0164138066926185
initial centroid 7: 6.486353414271516,-5.030963106559316,-5.9604258028778405,0.9059545748327194,4.411565170853445,-2.2142859888956887,8.228581289465058,4.308931852519473,-0.5165384151353529,-1.0285659173762336
------------------------------------------------------------------------------------
thresholdCondition: false
iteration: 24
bannedK: []
------------------------------------------------------------------------------------
Execution time: 697644 ms
------------------------------------------------------------------------------------
0       ,2.2381814,-7.741363,-3.4677613,-1.9219757,6.822761,-4.4848104,-0.20363973,9.869291,0.36753586,1.8536022
1       ,-7.605094,6.5392103,2.0942192,0.8643687,-3.1517825,-3.9124184,-1.6580057,3.6256034,7.530648,0.20138009
2       ,0.97384644,4.415411,1.9351876,-1.0352368,3.0934312,-2.3780427,-1.285756,-5.6599307,-3.2051454,1.5896926
3       ,3.6126328,-4.536159,-5.9334636,1.173113,4.788994,-1.194355,9.709334,3.739334,-0.46070236,-2.199235
4       ,-8.173112,-1.3408513,-1.419099,-0.13504809,-1.4698272,-3.760623,-1.4537437,7.900378,8.88746,0.06324896
5       ,2.6389823,-7.6030073,-3.8770854,-1.5506704,7.800458,-5.4007525,-0.4003144,9.48868,0.4114641,2.5871608
6       ,-8.089125,7.7062564,2.522569,4.423074,-9.719754,1.9118172,1.1422322,-6.8212905,-6.9631085,3.924268
7       ,4.3385134,-4.020276,-4.9644966,0.9627667,4.054101,-1.9772745,9.603395,3.6659274,-0.30199802,-2.0884295

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

initial centroid 0: 0.252240974969006,-7.61482804028166,-5.111915704038147,-1.3103735293722953,9.490381187033943,-5.596786233820085,0.7844860438874455,10.883796992980695,0.803031516183304,1.1093070382842376
initial centroid 1: -8.764542652961246,-2.035445000030825,-0.9792099677995822,-0.9900553249098016,0.09587844905831733,-3.9353994934607845,-2.239473835441383,8.378680594400555,8.67224896109167,-0.6587140630261639
initial centroid 2: -8.03769895704106,7.848402678196475,3.590724253389511,0.4441087107613271,-2.2851956799627864,-4.4304491610753995,-3.734048763459473,2.962198102754189,6.84925007191881,-0.10003686343192586
initial centroid 3: -4.9088447416672185,2.9099562515812245,-2.439817768661326,-9.86732207099034,-2.5405342411196097,4.848235711707403,-7.607698456788164,-6.0252551279735975,2.135248626583536,0.16651568421411722
initial centroid 4: 4.792360832200955,-4.977414608371578,-7.214155528435811,1.1728930278016498,4.574318158176093,-1.1902100129539999,7.700916419554503,6.1338246661009705,0.48841501559308387,-3.1220154115016983
initial centroid 5: 4.118572686886591,-3.450140792938944,-4.152094919017259,-0.4639180461716077,5.374206882791157,-2.0019050511109375,9.54322386948468,3.5913264161248435,-0.8308766411324751,-3.047560692999923
initial centroid 6: 3.2825801787773115,6.3878493744006475,4.397237863376663,1.9075295984570388,5.426513120653154,-3.120052383741402,-2.148385313145052,-2.2815237254468514,-3.5242784565821155,2.0413378030420635
initial centroid 7: 3.8518444029013605,-8.901288725456812,-2.9615304986438287,-1.888722677294711,6.290822098369906,-5.5806127887244585,-1.3055064280166557,11.387039673965031,1.7462398362842733,1.402175317955039

------------------------------------------------------------------------------------
thresholdCondition: false
iteration: 24
bannedK: []
------------------------------------------------------------------------------------
Execution time: 693547 ms
------------------------------------------------------------------------------------
0       ,2.0078835,-7.372475,-3.8843102,-1.545035,7.665948,-5.0261707,-0.34417832,9.634213,-0.030782597,1.989465
1       ,-7.889104,2.5991848,0.33755973,0.36466047,-2.3108077,-3.836515,-1.555875,5.7629867,8.20905,0.1323146
2       ,-8.08912,7.7062516,2.52257,4.423075,-9.7197485,1.9118154,1.1422322,-6.8212876,-6.9631085,3.9242656
3       ,-3.1279476,4.547526,-1.2249937,-8.830114,-2.0296836,4.7537603,-6.343336,-6.4733434,0.60079765,0.6410075
4       ,3.6788993,-4.5966763,-5.876615,1.2008997,4.600068,-1.5019858,9.903095,3.951378,-0.22226907,-2.1279817
5       ,4.349202,-3.875718,-4.910002,0.89986557,4.1983466,-1.6882377,9.342918,3.386439,-0.5846822,-2.1646097
6       ,3.0247474,4.3493586,3.5152805,2.8622072,5.654983,-5.9439473,1.2430339,-5.2532244,-5.1081147,2.0640335
7       ,2.8595035,-7.9611473,-3.4710722,-1.9180793,6.9776807,-4.870676,-0.26296344,9.718757,0.7969607,2.450957


    

In [ ]:
dataset 4
initial centroid 0: -0.8429810934357603,10.54093259171173,2.9778838175607985,-0.06616157199296124,-2.422184590462165
initial centroid 1: 5.033559197764801,-5.124983593003587,-6.374915044881804,1.8419570911760381,2.9456815487535555
initial centroid 2: -3.1729527347215356,5.845297886343832,-0.26947571313021035,-7.125496806785437,-2.2181559533445787
initial centroid 3: 3.269531230448045,-5.440026642036373,-5.134495257482021,2.186467781269413,0.9156171086935248
    
------------------------------------------------------------------------------------
thresholdCondition: true
iteration: 4
------------------------------------------------------------------------------------
Execution time: 122088 ms
------------------------------------------------------------------------------------

0       ,-1.529965,9.612745,3.68618,-0.38731667,-2.1630363
1       ,3.9294224,-4.266829,-5.457895,1.0405167,4.394837
2       ,-3.135665,4.584452,-1.2182578,-8.791461,-2.034061
3       ,4.7690434,-6.345762,-6.4811845,0.619356,0.6292616

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

initial centroid 0: -3.199704238101332,4.029711050566713,-1.2474668095808583,-8.866127123163764,-1.0290615413186297
initial centroid 1: -4.085513918435809,4.982635502951128,-2.3449224733225478,-7.983064588166816,0.1995556844595714
initial centroid 2: 3.8061491892272032,-6.611736395484486,-6.241494432469249,-0.4991056017814004,-0.01072966736421499
initial centroid 3: -1.520139781266249,8.74354525649184,4.082869470002171,-0.5958947819506307,-2.0646426978383965
    
------------------------------------------------------------------------------------
thresholdCondition: true
iteration: 12
bannedK: []
------------------------------------------------------------------------------------
Execution time: 332492 ms
------------------------------------------------------------------------------------

0       ,-2.856543,4.3165517,-0.763944,-9.010543,-2.485197
1       ,-3.4283144,4.865336,-1.6946098,-8.561803,-1.5610306
2       ,4.3491087,-5.305973,-5.969406,0.8300045,2.512652
3       ,-1.5299617,9.612741,3.6861987,-0.3873159,-2.1630383

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
initial centroid 0: -2.2548973332310287,8.821787247453173,3.205294310923002,2.346413634175293,-1.5503723536598333
initial centroid 1: 2.820752743818807,-2.3566125098415616,-5.299642254429959,0.23944492789265248,4.9395869413662306
initial centroid 2: 5.31274286773189,-5.994335914450367,-6.851740965093828,-0.1559586962458348,1.0759236332818727
initial centroid 3: -2.9308720880852492,3.9640294406905,-3.2330569723141456,-9.424019311646765,-2.5653598805200675

------------------------------------------------------------------------------------
thresholdCondition: true
iteration: 3
bannedK: []
------------------------------------------------------------------------------------
Execution time: 99634 ms
------------------------------------------------------------------------------------
0       ,-1.529965,9.612745,3.68618,-0.38731667,-2.1630363
1       ,3.9293292,-4.266625,-5.457774,1.0405903,4.3955307
2       ,4.768868,-6.3453083,-6.48098,0.61941713,0.629773
3       ,-3.1356597,4.5844474,-1.2182609,-8.791473,-2.034053


In [ ]:
dataset 5

initial centroid 0: -1.2942043667511918,8.476754941650592,4.07715519333386,-0.6400815511608613,-1.0382781542336184
initial centroid 1: -2.4438873935273264,7.9377182622684845,3.3800353455189085,2.268927472159402,-1.5179892045350711
initial centroid 2: -3.925469757103239,4.818777992946068,-2.5214967897430762,-8.130796939513152,-1.3652890884053073
initial centroid 3: -4.5990428017866725,3.128579689293902,-0.6290538048189702,-9.684863775124503,-3.42413788901181

------------------------------------------------------------------------------------
thresholdCondition: true
iteration: 2
bannedK: [1]
------------------------------------------------------------------------------------
Execution time: 78901 ms
------------------------------------------------------------------------------------

0       ,-1.5322648,9.620661,3.7083006,-0.37889704,-2.1542895
2       ,4.348412,-5.310598,-5.9810567,0.8279464,2.5078354
3       ,-3.1298027,4.5721827,-1.2323043,-8.807697,-2.03438

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

initial centroid 0: -4.277871038403616,4.90891186773226,-0.8620121866861106,-6.302312878065945,-1.5380079066376968
initial centroid 1: -3.761725287407666,4.298017036380228,-1.456885235720365,-8.368666741354653,-1.4193389576903508
initial centroid 2: 4.827575469034059,-6.077966557410835,-5.678332851179285,0.21715569872136103,1.6441322151005286
initial centroid 3: 4.463262355199181,-2.9088072483262257,-4.8118361333719255,2.1608233830398955,3.5648140311502186

------------------------------------------------------------------------------------
thresholdCondition: true
iteration: 3
------------------------------------------------------------------------------------
Execution time: 100091 ms
------------------------------------------------------------------------------------

0       ,-1.5322648,9.620661,3.7083006,-0.37889704,-2.1542895
1       ,-3.1297932,4.57219,-1.2323039,-8.807696,-2.0343673
2       ,4.7658534,-6.35037,-6.4971085,0.62498647,0.62488323
3       ,3.930158,-4.2688575,-5.4640627,1.0312765,4.3942637

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
initial centroid 0: -1.0763023323247658,10.27647763686678,5.28813973387516,0.5102661636855118,-2.561568374021032
initial centroid 1: 4.759161001664474,-5.683870481259819,-6.966558369379073,0.41405570522637813,0.6812064256662578
initial centroid 2: -4.304879622191988,9.411916232397962,4.112231926486618,-0.06868100737402721,-0.8768836527917023
initial centroid 3: -2.328915816766041,3.834182105484409,-3.5718179118580817,-9.249125352352783,-3.1360213577027185
------------------------------------------------------------------------------------
thresholdCondition: true
iteration: 16
bannedK: []
------------------------------------------------------------------------------------
Execution time: 441955 ms
------------------------------------------------------------------------------------

0       ,-0.93050706,9.840365,3.8557503,-0.23426266,-2.559844
1       ,4.34841,-5.3105836,-5.9810524,0.82794416,2.5078418
2       ,-2.1458807,9.396657,3.5579684,-0.52638423,-1.7407598
3       ,-3.1297874,4.5721765,-1.2323064,-8.807663,-2.034387

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
initial centroid 0: 4.670265456169583,-6.708099272968893,-6.257289263612719,-1.6688000119564776,1.1477215579006483
initial centroid 1: -4.8174439849579835,3.211024040196116,-0.9182785744747586,-8.478687999695005,-3.003951446242416
initial centroid 2: -1.457268317664442,10.18523869145868,3.0825713460419575,0.4207377161460871,-2.0340518393675664
initial centroid 3: 4.632672343160936,-7.579291813305605,-5.610686085300771,0.5469210085585372,0.5725039280902476
    
------------------------------------------------------------------------------------
thresholdCondition: true
iteration: 4
bannedK: []
------------------------------------------------------------------------------------
Execution time: 137493 ms
------------------------------------------------------------------------------------
0       ,3.9302847,-4.269027,-5.464449,1.0311736,4.3937507
1       ,-3.1297884,4.572197,-1.232308,-8.807668,-2.034377
2       ,-1.5322648,9.620661,3.7083006,-0.37889698,-2.1542895
3       ,4.7659984,-6.350788,-6.4969954,0.62497437,0.6243504
    

In [ ]:
dataset 6

initial centroid 0: -8.634015560295513,-0.6738581261669715,-2.639130557944144,1.2645780101898794,0.3240321639199579,-3.3815377784463205,-1.733078516464215,9.11417150606167,8.777434403033746,-0.37220238442615766
initial centroid 1: 4.403166161426696,-4.658278220731752,-4.711912850272834,1.8014917449731922,5.0449963675812,-1.3115758270541154,9.76043073236921,3.2428375499091078,-0.13239748358996908,-1.7042383635726368
initial centroid 2: -4.124401403947594,3.5722663792340663,-1.0592538668989562,-9.951220298821788,-2.502259809468514,3.297516740363695,-7.0154492038500305,-5.840589998772672,1.0970923294350712,0.9430940370098998
initial centroid 3: 2.951346844240383,5.8304150072987495,4.734964066912805,1.6239389662121608,6.616933245407909,-3.127468580658825,-3.1525100412378078,-6.204594082644949,-3.335829688618797,1.4655550041075602

------------------------------------------------------------------------------------
thresholdCondition: true
iteration: 1
------------------------------------------------------------------------------------
Execution time: 61078 ms
------------------------------------------------------------------------------------

0       ,-8.159067,-1.3247386,-1.376938,-0.12266235,-1.4829596,-3.750003,-1.4825004,7.8704357,8.882477,0.047107227
1       ,3.9384131,-4.2685857,-5.460119,1.0326508,4.3815465,-1.5382495,9.614856,3.7012916,-0.38186276,-2.1501098
2       ,-3.1324246,4.587036,-1.2359335,-8.810375,-2.0377498,4.7670445,-6.361585,-6.4912243,0.62885606,0.6333829
3       ,2.6856732,6.980909,4.4803767,2.217752,4.452146,-3.5458274,-2.7560244,-5.4305,-4.1145377,2.606655

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

initial centroid 0: -8.901966975357563,-2.1543373155235033,-1.6286288415976569,-0.0827542112549235,-1.8731494335566317,-2.7884615488875486,-0.8511617233653285,6.207258454527745,7.201358677727923,0.1523845960925469
initial centroid 1: -8.094276962448628,-1.8761794037944548,-2.594958016791877,0.22039685972446726,-1.0199086548956287,-3.0499572756746836,-0.6848323430843694,9.922782432979798,9.322750547684175,-1.3191746180639026
initial centroid 2: 3.9921297667757756,-5.503566691786497,-5.985887285651325,2.459167084863939,5.956001759533006,-0.3536545384675871,9.011547686225283,2.359051528558452,0.6024365926429184,-1.1762411766944472
initial centroid 3: -7.925303534512334,-1.8575100271442455,-3.0814380707617217,-0.5463841213722671,-0.1674448907788213,-3.339101239735586,-3.47879788360246,7.795007388635628,10.457009391943243,-1.222649579868401

------------------------------------------------------------------------------------
thresholdCondition: true
iteration: 21
------------------------------------------------------------------------------------
Execution time: 588331 ms
------------------------------------------------------------------------------------
#con così tante iterazioni ha beccato l'ottimo locale
#i centroidi sono diversi da quelli di prima e diversi da quelli di sklearn

0       ,-3.1324322,4.5870237,-1.2359356,-8.810393,-2.0377402,4.7670527,-6.3615794,-6.4912105,0.62885505,0.6333834
1       ,-8.300108,-1.120937,-1.3658936,-0.076111615,-1.6557349,-3.909123,-0.89113003,8.296484,8.803206,-0.089416
2       ,3.3120556,1.3561779,-0.48987696,1.6252018,4.4168415,-2.5420437,3.4294162,-0.86461556,-2.2482014,0.22827213
3       ,-8.021201,-1.5239589,-1.3877225,-0.16816783,-1.314072,-3.5944726,-2.0605807,7.4539356,8.959957,0.18056318


In [ ]:
dataset 7

initial centroid 0: 3.0176628704027992,-6.014227098121478,-6.9248140193801095,0.5755119987948385,1.4726660391096371,1.8360017573714744,5.794963505828053,4.413230615489118,2.99370054040094,3.955525346019776,-4.8875430268475455,-2.5441542523682092,-5.912486118417684,-3.600952383010065,2.672622600586746
initial centroid 1: 4.3704146725599715,-5.593073984906831,-3.897121913834627,-0.2733226343942725,3.8858752147784763,-1.4028228552660895,10.993472154116727,2.3181953875299173,-1.7485978943564868,-1.424305335143679,-3.6921245166087617,4.634393450236039,-0.24135233870998662,-8.419340742591128,-1.7312755604892187
initial centroid 2: 3.627375781571221,-7.481701792922758,-5.888257279652243,0.9446433061236842,1.4935247344558702,2.4886643827317694,6.590146227562344,6.48731704943747,-1.5595351787935927,5.102802172035392,-3.141734071052632,-3.610804950017614,-5.458373971021895,-5.006881054259558,1.44666612233424
initial centroid 3: -2.68435323074215,-0.8757470508900569,9.401574166183144,-0.042761380203724275,4.689174325590228,-8.872869667599025,5.59250311659353,1.5910834556153413,1.7817392957598157,-2.452426914507164,-2.743725174921907,-1.5581132403620255,2.741734051740508,8.769788059112923,2.036545602878201

------------------------------------------------------------------------------------
thresholdCondition: true
iteration: 2
------------------------------------------------------------------------------------
Execution time: 94138 ms
------------------------------------------------------------------------------------

0       ,-8.149434,-1.3132468,-1.3804992,-0.13382702,-1.4876983,-3.7583065,-1.4682003,7.861618,8.868348,0.029431412,2.4789543,-7.6897182,-3.646228,-1.7032071,7.3326683
1       ,3.9276276,-4.2800417,-5.456532,1.0185208,4.3938556,-1.531548,9.622474,3.7023559,-0.37325767,-2.1571841,-3.1363645,4.580754,-1.2253354,-8.807629,-2.04017
2       ,4.755704,-6.360988,-6.500428,0.6311076,0.6410948,2.695089,6.9779787,4.487228,2.2262943,4.4474187,-3.5400844,-2.7586787,-5.4263186,-4.127713,2.6079798
3       ,-4.98818,-0.34101027,9.712414,0.39015013,2.2521298,-7.5771494,6.513992,2.0672503,0.9048508,-3.1417446,-3.9157593,-1.6545041,3.6228528,7.5180326,0.1987698

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

initial centroid 0: 4.894029704151282,-5.424209252702675,-5.071826284418269,1.7495772248442798,5.650479572364027,-2.742254493127426,11.922370497773752,3.291184754270861,-0.8194541573346884,-2.657546413796058,-2.548792837328947,3.654452553444159,0.5084271179954847,-9.265991615315361,-1.9132929252591102
initial centroid 1: 5.235363527557873,-7.916190028496422,-4.7619332099720495,-0.03718144659027467,1.1018020087623366,0.993812060875592,6.649327072086052,4.1245227218977085,0.491722763815988,3.7501775609692385,-4.951919647597505,-3.1033941822773174,-6.604339349447395,-4.733646455525552,2.916591231541805
initial centroid 2: 3.9204552146891762,-5.369433823203275,-6.8483514111036445,3.0503654180579702,1.0007616115801108,2.2793704267152455,7.902568746962375,2.611705647272308,1.3610103706827736,2.8542020026355406,-3.7798055221155216,-2.644140852177412,-5.9178537203521895,-4.2972035637076225,2.126490276314196
initial centroid 3: 5.156764963580549,-6.533838017821954,-6.256298154015456,1.5000862674021516,1.7032888242656272,2.0605369141468897,7.271650781220453,4.738809912081779,2.5997533961243278,3.779581245088524,-3.564644899604062,-3.1420164656353617,-5.0862594737906175,-3.776654408104642,2.371911844166533

null pointer exception

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
con l implementazione che gestisce i centroidi che rimangono vuoti:

------------------------------------------------------------------------------------
thresholdCondition: false
iteration: 24
bannedK: [1]
------------------------------------------------------------------------------------
Execution time: 686363 ms
------------------------------------------------------------------------------------

0       ,4.3416553,-5.3205304,-5.9784718,0.8248098,2.517469,0.5817746,8.300256,4.094804,0.9265172,1.1451064,-3.3382223,0.9110499,-3.325812,-6.467668,0.28389806
2       ,-4.9881763,-0.34101117,9.712416,0.3901518,2.2521276,-7.577157,6.5139804,2.0672507,0.90485245,-3.1417432,-3.9157732,-1.6545137,3.6228719,7.5180144,0.19877087
3       ,-8.149384,-1.3132553,-1.3804954,-0.13382664,-1.4876978,-3.7583025,-1.4681982,7.86165,8.868332,0.029431451,2.4789388,-7.689714,-3.646215,-1.7032045,7.3326836

In [ ]:
dataset 8 (a lot of times this dataset bring the application to a fault: 'is running 9412608B beyond the PHYSICAL memory limit.')

initial centroid 0: 4.6095798486427935,-3.7860458637531265,-5.748058034054838,0.7080355603154999,4.217232876556384
initial centroid 1: -2.6968596211277838,-1.6168704640298897,7.723747662609652,8.079098800034934,0.5912006363060094
initial centroid 2: 3.480388006643849,7.51959444958803,4.13956734671835,0.1480514607284884,3.114324888588656
initial centroid 3: 6.1130469071122295,-5.311720017649892,-5.564684371142932,0.10192162422965967,1.9609599962596773
initial centroid 4: 3.511212087900705,-4.2035459020665025,-4.885041663091,1.3332711106690167,6.281186731728377
initial centroid 5: -1.7614064652097485,9.236057780361692,3.447569552794359,-0.5239297514841277,-2.444364631145712
initial centroid 6: -4.56930522616472,-1.6552857558165197,9.838377150850624,7.426876892979595,-0.34296148432773305
initial centroid 7: 1.5109790043472295,7.241945429969893,4.9476604321800455,1.5371293480342358,5.2744502571994785
------------------------------------------------------------------------------------
thresholdCondition: true
iteration: 5
bannedK: []
------------------------------------------------------------------------------------
Execution time: 172501 ms
------------------------------------------------------------------------------------
0       ,3.9292397,-4.266622,-5.457965,1.040636,4.3960094
1       ,-8.145465,-1.3157749,-1.3997796,-0.13640122,-1.5009581
2       ,-1.5300211,9.612667,3.6861827,-0.38724145,-2.1631782
3       ,4.768602,-6.345127,-6.4807625,0.6195398,0.6299691
4       ,-3.5354884,-2.7751527,-5.4271517,-4.1129155,2.6182938
5       ,-3.1355681,4.584405,-1.2182633,-8.791709,-2.0342417
6       ,-3.7583573,-1.4761814,7.8767467,8.883245,0.041510835
7       ,2.6964915,6.981748,4.4739814,2.2051966,4.459625


++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
initial centroid 0: -0.9102334403238016,9.244423213981818,3.2010792122793923,-1.229671463822617,-3.2491187232547416
initial centroid 1: 2.9756809686125294,6.425402176417987,4.295144855892931,3.460469076594931,3.233372154079674
initial centroid 2: -6.847476686952166,-3.994171685461971,-1.270934378712423,-0.8099969008517178,-0.6150902473581241
initial centroid 3: -2.3581410393325988,3.5670161945138603,-1.5654568708562389,-8.815638278546839,-1.400527585347458
initial centroid 4: -2.9773190469932773,-2.0252513633136493,9.05712700186545,8.046015467142917,-1.7249068910934973
initial centroid 5: 1.5033932687714422,6.840962101297056,6.083369399538519,4.04293820164928,4.84767184920305
initial centroid 6: -9.326185687918361,-0.5906953505547634,0.629987443109965,-0.9755333096322245,-0.356688518510228
initial centroid 7: -4.081566898811216,-1.667674388254236,-4.443130040248992,-4.684223463445348,1.6650624810920398

------------------------------------------------------------------------------------
thresholdCondition: false
iteration: 24
bannedK: []
------------------------------------------------------------------------------------
Execution time: 720206 ms
------------------------------------------------------------------------------------



++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

initial centroid 0: 4.392917473609717,-5.36866870617124,-5.897536137746582,2.4681892299423915,6.469311405793545
initial centroid 1: -9.519166598403606,-1.7517935068218229,-1.1728638829154105,-0.31475233385813833,-1.6919204993584622
initial centroid 2: -1.519434513967235,-3.936806417798839,-5.464728274034655,-3.5150746631863767,1.453693443242544
initial centroid 3: 4.376218650043559,-8.50150161236898,-5.948360789399101,1.057711166840439,-0.7864047155466511
initial centroid 4: -3.6348150331510394,-3.551604055779452,-4.928291222336842,-4.052613315818885,2.8714440437914295
initial centroid 5: 4.302856071874601,-8.677502985982308,-7.780817358045745,0.5645569332333772,-0.41125990227745834
initial centroid 6: 4.515792099694025,-5.536385339998651,-6.691088976385162,1.4361356993218815,0.10491271074090036
initial centroid 7: -2.0529443467106585,4.627608149055358,-0.3820268185309247,-7.955062329906419,-2.3292034109513304
    
------------------------------------------------------------------------------------
thresholdCondition: false
iteration: 24
bannedK: []
------------------------------------------------------------------------------------
Execution time: 699817 ms
------------------------------------------------------------------------------------
0       ,3.8779862,-4.1523795,-5.416221,1.0664237,4.6091495
1       ,-3.7583604,-1.476182,7.8767724,8.883241,0.041510683
2       ,-3.5657952,-2.7768674,-5.406732,-4.081385,2.5989175
3       ,4.5816474,-6.450962,-5.8289633,0.7022749,0.09055931
4       ,-5.6333427,1.6522485,-1.3033463,-4.481055,-1.7747511
5       ,5.054889,-6.4789405,-7.271864,0.5155011,0.749664
6       ,4.362138,-5.3129644,-5.8954697,0.7813358,2.4590836
7       ,0.58341277,8.297254,4.0801454,0.9090714,1.1483912
