In [1]:
from sklearn.datasets import make_blobs
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_samples, silhouette_score
from sklearn.cluster import AgglomerativeClustering

import matplotlib.pyplot as plt
import matplotlib.cm as cm
import numpy as np


In [3]:
X = [0 for i in range(9)]
y = [0 for i in range(9)]
#                0,    1,     2,     3,     4,      5,      6,      7,      8
n_samples_ = [1000, 5000, 10000, 10000, 50000, 100000, 100000, 100000, 100000]
n_features_ = [  5,    5,     5,    10,     5,      5,     10,     15,      5]
centers_ = [     4,    4,     4,     8,     4,      4,      4,      4,      8]

for i in range(9):
    X[i], y[i] = make_blobs(
        n_samples = n_samples_[i],
        n_features = n_features_[i],
        centers = centers_[i],
        cluster_std=(1),
        center_box=(-10.0, 10.0),
        shuffle=True,
        random_state=123,
    )

In [4]:
count = 0
for x in X:
    print("dataset: ", count)
    float_array = [[float(value) for value in sub_array] for sub_array in x.tolist()]
    file_path = 'C:/Users/matte/k-means/dataset' + str(count) + '.txt'
    print(file_path)
    with open(file_path, 'w') as file:
        for array in float_array:
            string = ""
            for element in array:
                string += str(element) + ','
            string = string[:-1]
            string += '\n'
            file.write(string)
    
    count = count + 1

dataset:  0
C:/Users/matte/k-means/dataset0.txt
dataset:  1
C:/Users/matte/k-means/dataset1.txt
dataset:  2
C:/Users/matte/k-means/dataset2.txt
dataset:  3
C:/Users/matte/k-means/dataset3.txt
dataset:  4
C:/Users/matte/k-means/dataset4.txt
dataset:  5
C:/Users/matte/k-means/dataset5.txt
dataset:  6
C:/Users/matte/k-means/dataset6.txt
dataset:  7
C:/Users/matte/k-means/dataset7.txt
dataset:  8
C:/Users/matte/k-means/dataset8.txt


In [9]:
centroids = [0 for i in range(9)]
for i in range(10):
    print("dataset: ", i)
    kmeans = KMeans(centers_[i])
    kmeans.fit(X[i])
    centroids[i] = kmeans.cluster_centers_
    print(centroids[i])

dataset:  0
[[ 4.93826966 -6.35118675 -6.39597854  0.67836025  0.65299858]
 [-3.15622754  4.5988347  -1.14809541 -8.74384277 -2.09275879]
 [-1.4775032   9.5263173   3.66962567 -0.26616827 -2.11147811]
 [ 3.83836441 -4.2416108  -5.43770762  0.977451    4.3439719 ]]
dataset:  1
[[-3.18146887  4.60971772 -1.21968646 -8.79173213 -2.00154981]
 [ 3.95579268 -4.29147542 -5.43365161  1.0660917   4.38170484]
 [-1.52271022  9.65889172  3.71025253 -0.37023597 -2.14602929]
 [ 4.77661959 -6.36896134 -6.55483353  0.63155244  0.5970093 ]]
dataset:  2
[[-3.1806054   4.63073329 -1.19677097 -8.77427662 -2.03987529]
 [ 3.95533053 -4.26459982 -5.44387483  1.0522834   4.38847823]
 [-1.55199083  9.62206898  3.67026929 -0.3731056  -2.15801427]
 [ 4.76307752 -6.3612275  -6.49521934  0.64517714  0.60878612]]
dataset:  3
[[-3.12794723  4.5475229  -1.22499337 -8.8301232  -2.02968515  4.75376045
  -6.34333332 -6.47334065  0.6007978   0.6410075 ]
 [ 3.97383168 -4.27945317 -5.45130485  1.06844459  4.42331014 -1.583

In [5]:
#scrip for evauluete calculation time of sklearn's Kmeans 0 1 2 4 5
import time

def time_evalueation(dataset_num):
    iter_num = 30
    time_execution = 0
    for i in range(iter_num):
        start = time.time()
        kmeans = KMeans(4, random_state=i)
        kmeans.fit(X[dataset_num])
        end = time.time()
        time_execution = time_execution + (end - start)

    print('dataset' + str(dataset_num) + ': ' + str(time_execution/iter_num))

time_evalueation(0)
time_evalueation(1)
time_evalueation(2)
time_evalueation(4)
time_evalueation(5)


dataset0: 0.064828888575236
dataset1: 0.05276029904683431
dataset2: 0.08367555936177572
dataset4: 0.33585414091746013
dataset5: 0.5790135065714518
